server:
  body_max: 150
  error_page:
    404: /www/error/404.html
    403: /www/error/403.html
  port: 8080
  server_name: localhost
  routes:
    endpoint: /
    type: GET, POST
    folder: /www
    directory_listing: true
    file_if_is_repertory: /www/index.html
    extention_for_cgi: .php
  routes:
    endpoint: /data
    type: GET, POST
    folder: /www/data
    directory_listing: false
    file_if_is_repertory: /www/data/index.html
    extention_for_cgi: .php
server:
  routes:
    endpoint: /data/file
    type: GET, POST, DELETE
    folder: /www/data/file